#!/usr/bin/perl

#prints out numbers in list that are above average

use strict;
use 5.010;

sub above_average
{
	my $average = total(@_) / @_;
	my @gt;
	foreach (@_)
	{
		if($_ > $average)
		{
			push @gt, $_;
		}
	}
	return @gt;
}

sub total
{
	my $total = 0;
	foreach (@_)
	{
		$total += $_;
	}
	return $total;
}

my @fred = above_average(1..10);
print "\@fred is @fred\n";
print "(Should be 6 7 8 9 10)\n";
my @barney = above_average(100, 1..10);
print "\@barney is @barney\n";
print "(Should be just 100)\n";
