#!/usr/bin/perl

#prints out name of last person "greeted"

use strict;
use 5.010;

sub greet
{
	state $check = 0;
	state $last;
	if($check == 0)
	{
		$check++;
		print "Hi $_[0]! You are the first one here!\n";
	}
	else
	{
		print "Hi $_[0]! $last is also here!\n";
	}
	$last = $_[0];
}

greet("Fred");
greet("Barney");
